//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1", ConfigurationName="OTWebServiceSoap")]
public interface OTWebServiceSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/AddObject")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    AddObjectResult AddObject(AddObjectData Object);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/ModifyObject")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    ModifyObjectResult ModifyObject(ModifyObjectData Object);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/RemoveObject")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    RemoveObjectResult RemoveObject(int ObjectID, bool UseTrashbin, bool IgnoreReferences);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/InvokeScript")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    InvokeScriptResult InvokeScript(InvokeScriptParameters Script);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/GetObjectList")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetObjectListResult GetObjectList(GetObjectListData Get);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class AddObjectData
{
    
    private object[] itemsField;
    
    private string folderPathField;
    
    private string fieldMappingField;
    
    private int saveExFlagsField;
    
    private string usernameField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddedAttachmentsVal", typeof(AddedAttachmentsVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceListVal", typeof(ReferenceListVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folderPath
    {
        get
        {
            return this.folderPathField;
        }
        set
        {
            this.folderPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fieldMapping
    {
        get
        {
            return this.fieldMappingField;
        }
        set
        {
            this.fieldMappingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int saveExFlags
    {
        get
        {
            return this.saveExFlagsField;
        }
        set
        {
            this.saveExFlagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class AddedAttachmentsVal
{
    
    private AddedAttachment[] attachmentsField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public AddedAttachment[] Attachments
    {
        get
        {
            return this.attachmentsField;
        }
        set
        {
            this.attachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class AddedAttachment
{
    
    private bool linkField;
    
    private string nameField;
    
    private string descriptionField;
    
    private string urlField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool link
    {
        get
        {
            return this.linkField;
        }
        set
        {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class TimeStampedMemoSection
{
    
    private System.DateTime dateField;
    
    private string userField;
    
    private string stateField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string user
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string state
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class TimeStampedMemoVal
{
    
    private TimeStampedMemoSection[] sectionField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Section", Order=0)]
    public TimeStampedMemoSection[] Section
    {
        get
        {
            return this.sectionField;
        }
        set
        {
            this.sectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class HistoryVal
{
    
    private HistoryItem[] historyItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("HistoryItem", Order=0)]
    public HistoryItem[] HistoryItem
    {
        get
        {
            return this.historyItemField;
        }
        set
        {
            this.historyItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class HistoryItem
{
    
    private System.DateTime dateField;
    
    private string descriptionField;
    
    private string newValueField;
    
    private string oldValueField;
    
    private string stateField;
    
    private string userField;
    
    private string userFieldField;
    
    private int actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime Date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string NewValue
    {
        get
        {
            return this.newValueField;
        }
        set
        {
            this.newValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string OldValue
    {
        get
        {
            return this.oldValueField;
        }
        set
        {
            this.oldValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string User
    {
        get
        {
            return this.userField;
        }
        set
        {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string UserField
    {
        get
        {
            return this.userFieldField;
        }
        set
        {
            this.userFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int action
    {
        get
        {
            return this.actionField;
        }
        set
        {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class Attachment
{
    
    private int attachmentIdField;
    
    private bool linkField;
    
    private string nameField;
    
    private string urlField;
    
    private string descriptionField;
    
    private System.DateTime creationDateField;
    
    private System.DateTime lastModificationField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int attachmentId
    {
        get
        {
            return this.attachmentIdField;
        }
        set
        {
            this.attachmentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool link
    {
        get
        {
            return this.linkField;
        }
        set
        {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime creationDate
    {
        get
        {
            return this.creationDateField;
        }
        set
        {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime lastModification
    {
        get
        {
            return this.lastModificationField;
        }
        set
        {
            this.lastModificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class AttachmentsVal
{
    
    private Attachment[] attachmentsField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public Attachment[] Attachments
    {
        get
        {
            return this.attachmentsField;
        }
        set
        {
            this.attachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ObjectData
{
    
    private object[] itemsField;
    
    private int idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AttachmentsVal", typeof(AttachmentsVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("HistoryVal", typeof(HistoryVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceListVal", typeof(ReferenceListVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("TimeStampedMemoVal", typeof(TimeStampedMemoVal), Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class BoolVal
{
    
    private string nameField;
    
    private bool valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public bool Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ByteVal
{
    
    private string nameField;
    
    private byte valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public byte Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class CurrencyVal
{
    
    private string nameField;
    
    private decimal valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public decimal Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class DateTimeVal
{
    
    private string nameField;
    
    private System.DateTime valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public System.DateTime Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class DoubleVal
{
    
    private string nameField;
    
    private double valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public double Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class LongIntVal
{
    
    private string nameField;
    
    private int valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public int Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class NullVal
{
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ReferenceListVal
{
    
    private string nameField;
    
    private int[] objectIdsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int[] objectIds
    {
        get
        {
            return this.objectIdsField;
        }
        set
        {
            this.objectIdsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ReferenceToUserVal
{
    
    private string nameField;
    
    private ValueType typeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ValueType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public enum ValueType
{
    
    /// <remarks/>
    groupname,
    
    /// <remarks/>
    userdisplayname,
    
    /// <remarks/>
    userloginname,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ReferenceVal
{
    
    private string nameField;
    
    private int objectIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int objectId
    {
        get
        {
            return this.objectIdField;
        }
        set
        {
            this.objectIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ShortIntVal
{
    
    private string nameField;
    
    private short valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public short Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class SingleVal
{
    
    private string nameField;
    
    private float valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public float Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class StringVal
{
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class GetObjectListResult
{
    
    private ObjectData[] objectField;
    
    private bool successField;
    
    private string errorMsgField;
    
    private int totalNumberResultsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Object", Order=0)]
    public ObjectData[] Object
    {
        get
        {
            return this.objectField;
        }
        set
        {
            this.objectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool success
    {
        get
        {
            return this.successField;
        }
        set
        {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string errorMsg
    {
        get
        {
            return this.errorMsgField;
        }
        set
        {
            this.errorMsgField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int totalNumberResults
    {
        get
        {
            return this.totalNumberResultsField;
        }
        set
        {
            this.totalNumberResultsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class RequiredField
{
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ObjectIDs
{
    
    private int[] objectIDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int[] objectIDs
    {
        get
        {
            return this.objectIDsField;
        }
        set
        {
            this.objectIDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class Filter
{
    
    private object[] itemsField;
    
    private string[] textField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class GetObjectListData
{
    
    private object itemField;
    
    private RequiredField[] requiredFieldField;
    
    private string folderPathField;
    
    private bool recursiveField;
    
    private bool getHistoryField;
    
    private bool getNoFieldsField;
    
    private int minimumIndexField;
    
    private int maximumRecordsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Filter", typeof(Filter), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ObjectIDs", typeof(ObjectIDs), Order=0)]
    public object Item
    {
        get
        {
            return this.itemField;
        }
        set
        {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RequiredField", Order=1)]
    public RequiredField[] RequiredField
    {
        get
        {
            return this.requiredFieldField;
        }
        set
        {
            this.requiredFieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string folderPath
    {
        get
        {
            return this.folderPathField;
        }
        set
        {
            this.folderPathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool recursive
    {
        get
        {
            return this.recursiveField;
        }
        set
        {
            this.recursiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool getHistory
    {
        get
        {
            return this.getHistoryField;
        }
        set
        {
            this.getHistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool getNoFields
    {
        get
        {
            return this.getNoFieldsField;
        }
        set
        {
            this.getNoFieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int minimumIndex
    {
        get
        {
            return this.minimumIndexField;
        }
        set
        {
            this.minimumIndexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int maximumRecords
    {
        get
        {
            return this.maximumRecordsField;
        }
        set
        {
            this.maximumRecordsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class InvokeScriptResult
{
    
    private ScriptParameters parametersField;
    
    private bool successField;
    
    private string errorMsgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ScriptParameters Parameters
    {
        get
        {
            return this.parametersField;
        }
        set
        {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool success
    {
        get
        {
            return this.successField;
        }
        set
        {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string errorMsg
    {
        get
        {
            return this.errorMsgField;
        }
        set
        {
            this.errorMsgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ScriptParameters
{
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class InvokeScriptParameters
{
    
    private ScriptParameters parametersField;
    
    private string nameField;
    
    private ScriptExecutionSite runAtField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ScriptParameters Parameters
    {
        get
        {
            return this.parametersField;
        }
        set
        {
            this.parametersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ScriptExecutionSite runAt
    {
        get
        {
            return this.runAtField;
        }
        set
        {
            this.runAtField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public enum ScriptExecutionSite
{
    
    /// <remarks/>
    Default,
    
    /// <remarks/>
    Server,
    
    /// <remarks/>
    Client,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class RemoveObjectResult
{
    
    private bool successField;
    
    private string errorMsgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool success
    {
        get
        {
            return this.successField;
        }
        set
        {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string errorMsg
    {
        get
        {
            return this.errorMsgField;
        }
        set
        {
            this.errorMsgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ModifyObjectResult
{
    
    private bool successField;
    
    private string errorMsgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool success
    {
        get
        {
            return this.successField;
        }
        set
        {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string errorMsg
    {
        get
        {
            return this.errorMsgField;
        }
        set
        {
            this.errorMsgField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ReferenceListModificationsVal
{
    
    private string nameField;
    
    private int[] addedObjectIdsField;
    
    private int[] removedObjectIdsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int[] addedObjectIds
    {
        get
        {
            return this.addedObjectIdsField;
        }
        set
        {
            this.addedObjectIdsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int[] removedObjectIds
    {
        get
        {
            return this.removedObjectIdsField;
        }
        set
        {
            this.removedObjectIdsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ID
{
    
    private int valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public int Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ModifiedAttachment
{
    
    private int attachmentIdField;
    
    private bool linkField;
    
    private string nameField;
    
    private string descriptionField;
    
    private string urlField;
    
    private byte[] valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int attachmentId
    {
        get
        {
            return this.attachmentIdField;
        }
        set
        {
            this.attachmentIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool link
    {
        get
        {
            return this.linkField;
        }
        set
        {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
    public byte[] Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class AttachmentModificationsVal
{
    
    private AddedAttachment[] addedAttachmentsField;
    
    private ModifiedAttachment[] modifiedAttachmentsField;
    
    private ID[] deletedAttachmentsField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public AddedAttachment[] AddedAttachments
    {
        get
        {
            return this.addedAttachmentsField;
        }
        set
        {
            this.addedAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public ModifiedAttachment[] ModifiedAttachments
    {
        get
        {
            return this.modifiedAttachmentsField;
        }
        set
        {
            this.modifiedAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    public ID[] DeletedAttachments
    {
        get
        {
            return this.deletedAttachmentsField;
        }
        set
        {
            this.deletedAttachmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class ModifyObjectData
{
    
    private object[] itemsField;
    
    private int objectIdField;
    
    private int saveExFlagsField;
    
    private string usernameField;
    
    private string passwordField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AttachmentModificationsVal", typeof(AttachmentModificationsVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceListModificationsVal", typeof(ReferenceListModificationsVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int objectId
    {
        get
        {
            return this.objectIdField;
        }
        set
        {
            this.objectIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int saveExFlags
    {
        get
        {
            return this.saveExFlagsField;
        }
        set
        {
            this.saveExFlagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username
    {
        get
        {
            return this.usernameField;
        }
        set
        {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
public partial class AddObjectResult
{
    
    private bool successField;
    
    private int objectIdField;
    
    private string errorMsgField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool success
    {
        get
        {
            return this.successField;
        }
        set
        {
            this.successField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int objectId
    {
        get
        {
            return this.objectIdField;
        }
        set
        {
            this.objectIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string errorMsg
    {
        get
        {
            return this.errorMsgField;
        }
        set
        {
            this.errorMsgField = value;
        }
    }
}
