//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1", ConfigurationName="ServiceReference1.OTWebServiceSoap")]
    public interface OTWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/AddObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.AddObjectResult> AddObjectAsync(ServiceReference1.AddObjectData Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/ModifyObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ModifyObjectResult> ModifyObjectAsync(ServiceReference1.ModifyObjectData Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/RemoveObject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.RemoveObjectResult> RemoveObjectAsync(int ObjectID, bool UseTrashbin, bool IgnoreReferences);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/InvokeScript", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.InvokeScriptResult> InvokeScriptAsync(ServiceReference1.InvokeScriptParameters Script);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.omninet.de/OtWebSvc/v1/GetObjectList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.GetObjectListResult> GetObjectListAsync(ServiceReference1.GetObjectListData Get);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class AddObjectData
    {
        
        private object[] itemsField;
        
        private string folderPathField;
        
        private string fieldMappingField;
        
        private int saveExFlagsField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddedAttachmentsVal", typeof(AddedAttachmentsVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceListVal", typeof(ReferenceListVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folderPath
        {
            get
            {
                return this.folderPathField;
            }
            set
            {
                this.folderPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fieldMapping
        {
            get
            {
                return this.fieldMappingField;
            }
            set
            {
                this.fieldMappingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int saveExFlags
        {
            get
            {
                return this.saveExFlagsField;
            }
            set
            {
                this.saveExFlagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class AddedAttachmentsVal
    {
        
        private AddedAttachment[] attachmentsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public AddedAttachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class AddedAttachment
    {
        
        private bool linkField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string urlField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class TimeStampedMemoSection
    {
        
        private System.DateTime dateField;
        
        private string userField;
        
        private string stateField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class TimeStampedMemoVal
    {
        
        private TimeStampedMemoSection[] sectionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Section", Order=0)]
        public TimeStampedMemoSection[] Section
        {
            get
            {
                return this.sectionField;
            }
            set
            {
                this.sectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class HistoryVal
    {
        
        private HistoryItem[] historyItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("HistoryItem", Order=0)]
        public HistoryItem[] HistoryItem
        {
            get
            {
                return this.historyItemField;
            }
            set
            {
                this.historyItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class HistoryItem
    {
        
        private System.DateTime dateField;
        
        private string descriptionField;
        
        private string newValueField;
        
        private string oldValueField;
        
        private string stateField;
        
        private string userField;
        
        private string userFieldField;
        
        private int actionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NewValue
        {
            get
            {
                return this.newValueField;
            }
            set
            {
                this.newValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OldValue
        {
            get
            {
                return this.oldValueField;
            }
            set
            {
                this.oldValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string User
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string UserField
        {
            get
            {
                return this.userFieldField;
            }
            set
            {
                this.userFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class Attachment
    {
        
        private int attachmentIdField;
        
        private bool linkField;
        
        private string nameField;
        
        private string urlField;
        
        private string descriptionField;
        
        private System.DateTime creationDateField;
        
        private System.DateTime lastModificationField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int attachmentId
        {
            get
            {
                return this.attachmentIdField;
            }
            set
            {
                this.attachmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime creationDate
        {
            get
            {
                return this.creationDateField;
            }
            set
            {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime lastModification
        {
            get
            {
                return this.lastModificationField;
            }
            set
            {
                this.lastModificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class AttachmentsVal
    {
        
        private Attachment[] attachmentsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Attachment[] Attachments
        {
            get
            {
                return this.attachmentsField;
            }
            set
            {
                this.attachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ObjectData
    {
        
        private object[] itemsField;
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentsVal", typeof(AttachmentsVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("HistoryVal", typeof(HistoryVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceListVal", typeof(ReferenceListVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("TimeStampedMemoVal", typeof(TimeStampedMemoVal), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class BoolVal
    {
        
        private string nameField;
        
        private bool valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public bool Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ByteVal
    {
        
        private string nameField;
        
        private byte valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public byte Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class CurrencyVal
    {
        
        private string nameField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class DateTimeVal
    {
        
        private string nameField;
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public System.DateTime Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class DoubleVal
    {
        
        private string nameField;
        
        private double valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public double Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class LongIntVal
    {
        
        private string nameField;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class NullVal
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ReferenceListVal
    {
        
        private string nameField;
        
        private int[] objectIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int[] objectIds
        {
            get
            {
                return this.objectIdsField;
            }
            set
            {
                this.objectIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ReferenceToUserVal
    {
        
        private string nameField;
        
        private ValueType typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ValueType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public enum ValueType
    {
        
        /// <remarks/>
        groupname,
        
        /// <remarks/>
        userdisplayname,
        
        /// <remarks/>
        userloginname,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ReferenceVal
    {
        
        private string nameField;
        
        private int objectIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ShortIntVal
    {
        
        private string nameField;
        
        private short valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public short Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class SingleVal
    {
        
        private string nameField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class StringVal
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class GetObjectListResult
    {
        
        private ObjectData[] objectField;
        
        private bool successField;
        
        private string errorMsgField;
        
        private int totalNumberResultsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object", Order=0)]
        public ObjectData[] Object
        {
            get
            {
                return this.objectField;
            }
            set
            {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int totalNumberResults
        {
            get
            {
                return this.totalNumberResultsField;
            }
            set
            {
                this.totalNumberResultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class RequiredField
    {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ObjectIDs
    {
        
        private int[] objectIDsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int[] objectIDs
        {
            get
            {
                return this.objectIDsField;
            }
            set
            {
                this.objectIDsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class Filter
    {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class GetObjectListData
    {
        
        private object itemField;
        
        private RequiredField[] requiredFieldField;
        
        private string folderPathField;
        
        private bool recursiveField;
        
        private bool getHistoryField;
        
        private bool getNoFieldsField;
        
        private int minimumIndexField;
        
        private int maximumRecordsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Filter", typeof(Filter), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ObjectIDs", typeof(ObjectIDs), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RequiredField", Order=1)]
        public RequiredField[] RequiredField
        {
            get
            {
                return this.requiredFieldField;
            }
            set
            {
                this.requiredFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string folderPath
        {
            get
            {
                return this.folderPathField;
            }
            set
            {
                this.folderPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool recursive
        {
            get
            {
                return this.recursiveField;
            }
            set
            {
                this.recursiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool getHistory
        {
            get
            {
                return this.getHistoryField;
            }
            set
            {
                this.getHistoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool getNoFields
        {
            get
            {
                return this.getNoFieldsField;
            }
            set
            {
                this.getNoFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int minimumIndex
        {
            get
            {
                return this.minimumIndexField;
            }
            set
            {
                this.minimumIndexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int maximumRecords
        {
            get
            {
                return this.maximumRecordsField;
            }
            set
            {
                this.maximumRecordsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class InvokeScriptResult
    {
        
        private ScriptParameters parametersField;
        
        private bool successField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScriptParameters Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ScriptParameters
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class InvokeScriptParameters
    {
        
        private ScriptParameters parametersField;
        
        private string nameField;
        
        private ScriptExecutionSite runAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ScriptParameters Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ScriptExecutionSite runAt
        {
            get
            {
                return this.runAtField;
            }
            set
            {
                this.runAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public enum ScriptExecutionSite
    {
        
        /// <remarks/>
        Default,
        
        /// <remarks/>
        Server,
        
        /// <remarks/>
        Client,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class RemoveObjectResult
    {
        
        private bool successField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ModifyObjectResult
    {
        
        private bool successField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ReferenceListModificationsVal
    {
        
        private string nameField;
        
        private int[] addedObjectIdsField;
        
        private int[] removedObjectIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int[] addedObjectIds
        {
            get
            {
                return this.addedObjectIdsField;
            }
            set
            {
                this.addedObjectIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int[] removedObjectIds
        {
            get
            {
                return this.removedObjectIdsField;
            }
            set
            {
                this.removedObjectIdsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ID
    {
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ModifiedAttachment
    {
        
        private int attachmentIdField;
        
        private bool linkField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string urlField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int attachmentId
        {
            get
            {
                return this.attachmentIdField;
            }
            set
            {
                this.attachmentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool link
        {
            get
            {
                return this.linkField;
            }
            set
            {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class AttachmentModificationsVal
    {
        
        private AddedAttachment[] addedAttachmentsField;
        
        private ModifiedAttachment[] modifiedAttachmentsField;
        
        private ID[] deletedAttachmentsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public AddedAttachment[] AddedAttachments
        {
            get
            {
                return this.addedAttachmentsField;
            }
            set
            {
                this.addedAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ModifiedAttachment[] ModifiedAttachments
        {
            get
            {
                return this.modifiedAttachmentsField;
            }
            set
            {
                this.modifiedAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public ID[] DeletedAttachments
        {
            get
            {
                return this.deletedAttachmentsField;
            }
            set
            {
                this.deletedAttachmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class ModifyObjectData
    {
        
        private object[] itemsField;
        
        private int objectIdField;
        
        private int saveExFlagsField;
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentModificationsVal", typeof(AttachmentModificationsVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("BoolVal", typeof(BoolVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ByteVal", typeof(ByteVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("CurrencyVal", typeof(CurrencyVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DateTimeVal", typeof(DateTimeVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DoubleVal", typeof(DoubleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("LongIntVal", typeof(LongIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("NullVal", typeof(NullVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceListModificationsVal", typeof(ReferenceListModificationsVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceToUserVal", typeof(ReferenceToUserVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ReferenceVal", typeof(ReferenceVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ShortIntVal", typeof(ShortIntVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SingleVal", typeof(SingleVal), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("StringVal", typeof(StringVal), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int saveExFlags
        {
            get
            {
                return this.saveExFlagsField;
            }
            set
            {
                this.saveExFlagsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.omninet.de/OtWebSvc/v1")]
    public partial class AddObjectResult
    {
        
        private bool successField;
        
        private int objectIdField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int objectId
        {
            get
            {
                return this.objectIdField;
            }
            set
            {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OTWebServiceSoapChannel : ServiceReference1.OTWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OTWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.OTWebServiceSoap>, ServiceReference1.OTWebServiceSoap
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OTWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OTWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), OTWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OTWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OTWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AddObjectResult> AddObjectAsync(ServiceReference1.AddObjectData Object)
        {
            return base.Channel.AddObjectAsync(Object);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ModifyObjectResult> ModifyObjectAsync(ServiceReference1.ModifyObjectData Object)
        {
            return base.Channel.ModifyObjectAsync(Object);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.RemoveObjectResult> RemoveObjectAsync(int ObjectID, bool UseTrashbin, bool IgnoreReferences)
        {
            return base.Channel.RemoveObjectAsync(ObjectID, UseTrashbin, IgnoreReferences);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.InvokeScriptResult> InvokeScriptAsync(ServiceReference1.InvokeScriptParameters Script)
        {
            return base.Channel.InvokeScriptAsync(Script);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.GetObjectListResult> GetObjectListAsync(ServiceReference1.GetObjectListData Get)
        {
            return base.Channel.GetObjectListAsync(Get);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OTWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OTWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OTWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://shd.digdes.com/OTWS/v1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OTWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://shd.digdes.com/OTWS/v1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OTWebServiceSoap,
            
            OTWebServiceSoap12,
        }
    }
}
